# Generated by Django 4.2 on 2023-04-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ad_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=20),
        ),
        migrations.AlterField(
            model_name='ads',
            name='type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment')], default='house', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
