# Generated by Django 4.2 on 2023-05-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ads_ad_type_alter_ads_type_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('id_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ads')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'unique_together': {('id_ad', 'date', 'time')},
            },
        ),
    ]
